### ISSUE TITLE
Crash launching application - getDisplayName

### ISSUE THREAD

**Issue by penkesiva** [penkesiva/testprep#37]
11808071-01-09 22:44:30.134  1260  2499 I ActivityManager: KPU : put [com.android.defcontainer] : 0 K
11808164-01-09 22:44:30.134  1260  2499 I ActivityManager: Killing 3506:com.android.defcontainer/u0a17 (adj 906): DHA:empty #25
11808283-01-09 22:44:30.135  4251  4289 D AcmsKeyStoreHelper:  getKeyStoreForApplication Exit
11808368-01-09 22:44:30.135  4251  4289 I AcmsCertificateMngr: getKeyStoreForApplication success 
11808457-01-09 22:44:30.135  4251  4289 D AcmsCore: Decremented Counter Value : AcmsCoreHandler.handleMessage=>1
11808561-01-09 22:44:30.135  4251  4289 D AcmsServiceMonitor: AcmsServiceMonitor.getAcmsSvcMonitor() - Enter
11808661-01-09 22:44:30.135  4251  4289 D AcmsServiceMonitor: Decrementing - Counter value: 0
11808746-01-09 22:44:30.135  4251  4289 D AcmsServiceMonitor: Counter value is 0: Stopping ACMS service with ID 1
11808851-01-09 22:44:30.136  4349  4349 D AssistantMenuApp: onCreate , UI version : 9.0
11808930-01-09 22:44:30.137  4223  4223 D AndroidRuntime: Shutting down VM
11808996:01-09 22:44:30.137  4223  4223 E AndroidRuntime: FATAL EXCEPTION: main
11809067-01-09 22:44:30.137  4223  4223 E AndroidRuntime: Process: ee.testprep, PID: 4223
11809148-01-09 22:44:30.137  4223  4223 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ee.testprep/ee.testprep.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.FirebaseUser.getDisplayName()' on a null object reference
11809469-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
11809597-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
11809724-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
11809830-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
11809952-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11810058-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11810151-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
11810262-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11810362-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11810487-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11810602-01-09 22:44:30.137  4223  4223 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.FirebaseUser.getDisplayName()' on a null object reference
11810828-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at ee.testprep.MainActivity.loadNavHeader(MainActivity.java:383)
11810943-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at ee.testprep.MainActivity.onCreate(MainActivity.java:189)
11811053-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7174)
11811161-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
11811290-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
11811418-01-09 22:44:30.137  4223  4223 E AndroidRuntime: 	... 9 more
11811479-01-09 22:44:30.140  1260  2499 D Debug   : !@DumpState : SHIP

**Comment by penkesiva** [comment]
UserName is now getting updated on HomeFragment iso navDrawer
